# .streamlit/secrets.toml

[general]
email = "nikitha.s.2022.cse@ritchennai.edu.in"
github = "https://github.com/stargalax"
linkedIn= "https://linkedin.com/in/nikitha-s-564567261"


[certifications]
oracle_dashboard = "https://mylearn.oracle.com/ou/dashboard"
ibm_dashboard = "https://skills.yourlearning.ibm.com/progress/detail"
ml_dashboard = "https://skillbuilder.aws/training-activity"
analytics_eng = "https://www.linkedin.com/learning/certificates/449d11abbf12143d71347346e44ba567660e44d6d00fad21db0349a692b8eec4?trk=share_certificate"
excel = "https://www.linkedin.com/learning/certificates/06d6f7199b79c2b977676adb9237f45a1311097a8ba1c91bc4bccd446bd5d0d6?trk=share_certificate"
