# .streamlit/secrets.toml

[general]
email = "nikitha.s.2022.cse@ritchennai.edu.in"
github = "https://github.com/stargalax"
linkedIn= "https://linkedin.com/in/nikitha-s-564567261"


[certifications]
oracle_dashboard = "https://mylearn.oracle.com/ou/dashboard"
ibm_dashboard = "https://skills.yourlearning.ibm.com/progress/detail"
ml_dashboard = "https://skillbuilder.aws/training-activity"
